### ISSUE TITLE
Can't publish the config file.

### ISSUE THREAD

**Issue by anchan42** [fedeisas/laravel-mail-css-inliner#312] opened 2023-08-07 09:07 UTC
Running this `php artisan vendor: publish --provider='Fedeisas\LaravelMailCssInliner\LaravelMailCssInlinerServiceProvider'`
Return this error:    INFO  No publishable resources for tag [].
There is no config file showing up in the config directory. This is with Laravel 10.

**Comment by kirkbushell** [comment] 2023-09-12 00:33
You've got a space between vendor: and publish.

**Comment by DannyvdSluijs** [comment] 2023-09-18 09:13
@anchan42 did the comment from @kirkbushell help you?

I've recently created a [Laravel10MailCssInliner](https://github.com/DannyvdSluijs/Laravel10MailCssInliner) playground for which I've ran the same command without any issues.  I would be included to close the issue if no further details or reproduction steps can be shared.

**Comment by DannyvdSluijs** [comment] 2023-11-27 08:24
Closing issue for now due to lack of feedback. Feel free to re-open with new information when needed.

**Closed by DannyvdSluijs** 2023-11-27 08:24 UTC
Labels: Feedback needed
